### ISSUE TITLE
Balance Issue: Gold Nuggets More Expensive Than Gold Ingots

### ISSUE THREAD

**Issue by CaitlinTheAwesome** [LordMonoxide/gradient#216]
So right now the recipe of 1 ingot = 9 nuggets is missing/disabled, which is kind of a nasty balance issue, because the only ways to get nuggets right now are:
- Finding them in dungeons (=rarer than ingots, which can be mined)
- Melting down gold armor/tools (in which case using ingots would still be cheaper than nuggets cause you get 1 nugget from melting down any tool/armor piece)

But most recipes assume that gold nuggets are easy to come by, at least in mid-late game:
- Horse breeding: golden carrots take 8 gold nuggets each, need 2 golden carrots for breeding
- Glistering melon: 8 nuggets (forestry substitutes 8 honey drops)
- Bibliocraft fancy lamp: 2 nuggets
- Bibliocraft monocle: 4 nuggets
- Raw ironwood materials (for making ironwood ingots out of): 1 nugget per ingot
- Fairy lights ornate lantern: 3 nuggets each (and iirc one alone is useless, these are string lights... so 3x however many lights you're gonna have)
- Binnie's genetics polymerization: gold nuggets appear to be used for EVERYTHING

Without a reliable way to get gold nuggets, some of these things are kinda way too difficult to acquire for what they are...

**Comment by LordMonoxide** [comment]
You also get nuggets from breaking ores with a stone hammer, so you can do that for the time being

**Comment by LordMonoxide** [comment]
My first idea was a crafting recipe, `1 ingot + hammer -> 4 nuggets`.  There are two kinds of hammers, one is the stone hammer you use at the start of the game, and the other is a forge hammer.  The issue is, the forge hammer is already used in a recipe identical to that to hammer ingots into plates, and the stone hammer breaks after 15? uses...

I had a second idea though, but I'd need opinions/help fleshing this out... we could turn the stone hammer into a full-blown second type of digging tool (mining hammer, or whatever).  The metal mining hammers could do something like dig 3x3, but still only give you pebbles/nuggets/whatever like the regular stone hammer.

Thoughts? @CaitlinTheAwesome @Nexses

**Comment by LordMonoxide** [comment]
(Temporary?) solution: use a pickaxe in the recipe
